ALTER TABLE orders
ADD COLUMN IF NOT EXISTS payment_channel VARCHAR(32);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS payment_trade_no VARCHAR(64);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
