"""add expire_time to orders

Revision ID: 506f40a75657
Revises: 87fb99f769a5
Create Date: 2026-02-28 02:15:49.195997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506f40a75657'
down_revision = '87fb99f769a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expire_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('expire_time')

    # ### end Alembic commands ###
