"""add condition field to items

Revision ID: 73a0a420c68d
Revises: 2ff1d58aae0a
Create Date: 2026-02-27 01:10:55.391428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a0a420c68d'
down_revision = '2ff1d58aae0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
