"""add risk control and time location features

Revision ID: a1b2c3d4e5f6
Revises: 506f40a75657
Create Date: 2026-02-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '506f40a75657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create risk_logs table
    op.create_table('risk_logs',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('action_type', sa.String(length=32), nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('device_id', sa.String(length=128), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('risk_score', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_logs_created_at'), 'risk_logs', ['created_at'], unique=False)

    # Create user_risk_tags table
    op.create_table('user_risk_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('tag_type', sa.String(length=32), nullable=False),
        sa.Column('severity', sa.String(length=16), nullable=True),
        sa.Column('detail', sa.Text(), nullable=True),
        sa.Column('auto_tagged', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_risk_tags_user_id'), 'user_risk_tags', ['user_id'], unique=False)

    # Add time-space fields to items table
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_time_slots', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('preferred_locations', postgresql.ARRAY(sa.String()), nullable=True))

    # Add time-space fields to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usual_time_slots', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('usual_locations', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove time-space fields from users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('usual_locations')
        batch_op.drop_column('usual_time_slots')

    # Remove time-space fields from items table
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('preferred_locations')
        batch_op.drop_column('available_time_slots')

    # Drop user_risk_tags table
    op.drop_index(op.f('ix_user_risk_tags_user_id'), table_name='user_risk_tags')
    op.drop_table('user_risk_tags')

    # Drop risk_logs table
    op.drop_index(op.f('ix_risk_logs_created_at'), table_name='risk_logs')
    op.drop_table('risk_logs')

    # ### end Alembic commands ###
